language: php
php:
  - 5.3

branches:
  only:
    - master
    - develop

before_script: phpenv config-add misc/travis-phpconfig.ini
script: phpunit --coverage-text

services: mongodb

notifications:
  email:
    - nick@nicktemple.com
